name: shelf_host_validation
description: Validates the 'Host' and 'Referer' Header so that DNS Rebinding Attacks wont work.
version: 1.1.0
homepage: https://jxstxn.de
repository: https://github.com/jxstxn1/shelf_host_validation
issue_tracker: https://github.com/jxstxn1/shelf_host_validation/issues

topics:
 - shelf
 - dart_frog
 - middleware
 - security
 - dns_rebinding

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  shelf: ^1.3.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.7